#+OPTIONS: toc:nil \n:t
title: 那时候我含泪发誓各位必须看到我
date: 2018-09-01
updated:
comments: true
tags:
  - zen
layout: post
------
今天 2018 年 9 月 1 日，开学的日子，正好开始搭建这个新的博客。虽然早已不是学生，也算一个新的开始。有所感，写下这篇博文。

#+HTML: <!-- more -->
放弃了 =分类= 这个设置，所有的分类全部通过 =标签= 来处理。顶部的导航栏只设置了目前只设置了两个基于 =标签= 的导航，=学海= 和 =心法= 。

* 学海
=学海= 中准确来说是我自己的学习笔记，有些是 =备忘= ，主要提供自己日后参考；有些是 =教程= ，其实也是在学习的时候做出的输出。无论是 =备忘= 还是 =教程= 都关乎于技术，但不局限于 IT。

=教程= 类的文章是经过整理的，比较系统，适合想入门的读者。俗话说万事开头难，告诉你某技术或工具 *应该怎样用* 不如告诉你 *它能做什么* 。有如 =雪球读书法= 所言，读一本书先直观的鸟瞰一遍再精读，远比一来就一字一句深究来得更深刻。

=备忘= 则是有了一定基础（看得懂就叫基础）之后再来阅读会引发 =碰撞效应= 的类目。除了作为自己的备忘，也希望能与读者进行交流和互相嘲讽。所以备忘类的文章可能并不适合新手阅读。

例如本站基于的 =Hexo= 静态网站生成器，*如果你连"静态"二字都不太明白，或者对 Shell 一点概念都没有*，请你使用 [[https://www.blogger.com/about/?r=1-null_user][Blogger]] [[https://medium.com/][Medium]] [[https://zh-cn.wordpress.com/][WordPress]] 等工具，方便易用，无需部署，图形界面上点点点即可。不要在 Hexo 上浪费时间，它并不比前者更优秀。没有更优秀那为什么火？等到对命令行、服务器、Apache(nginx)、Git、HTML、CSS等不再陌生，自然也就明白了。

其实以前我也写过一篇"零基础搭建教程"，力求"零基础"，事无巨细的写，配图配命令，恨不得读者可以直接复制粘贴搞定一切。问题是搭建完成后呢，一但遇到问题"零基础"自己根本无法解决，也羞于提问，热度一过干脆博客也不写了。

*我觉得这是在带着别人兜圈子。*

*无论使用什么工具，写博客最重要的是"写"，只要能做到 "Keep Blogging"，用什么工具都是次要的。*

所以这个博客未来的所有 =备忘= 类博文我都会力求简洁，主要是提供一套流程、一些思路，和遇到问题后我的解决方法，也正因为如此很难再称之为"教程"，要知道 *最好的教程一定是官方文档* 。套用我写给落格输入法作者的一句话，懂的自然懂，不懂则问一问自己是不是自己的基础知识还不足以理解，而不是责怪作者写得太难。

至于如何区分，标题没有写 =教程= 两个字的，通通属于备忘，兴许哪一天会写一篇对应的教程也说不一定。博客嘛，难得有一块属于自己的地方，还不允许自己做主了？！

* 心法
=心法= 则是心有所感。从象牙塔毕业十年，在六个行业打过卡，经历过上至创始人下到出纳几乎所有工种，有一些经验和随想，在自我反思的时候，也就形成了 =笔记= 。

当然也会有一些 BB (Bark Bark)，比如这篇。

=心法= 的全称应该是 =心内求法=，并非遁入空门，而是人贵在自知。

如果说 =学海= 是我的 =器= ，那么 =心法= 便是我的 =术= 。至于 =道= ，等我再悟它个十年再说吧。

* 版权
每篇博文最下面都有版权说明。也可以点击侧边栏里面的 =cc= 图标查看具体内容。总结一下就是不可用于商业用途，我自己还没靠码字挣到钱呢。但可随意转载分享，注明出处即可。热度是每个博主能坚持写作的最大动力，现代社会要讲究环保，可持续发展才是硬道理嘛。

{% blockquote 陈奕迅, 浮夸 %}
那时候我含泪发誓各位必须看到我。
{% endblockquote %}
